"""init_users_tickers_user_id_fk

Revision ID: cf6294f3f61a
Revises: 
Create Date: 2026-05-18 14:07:55.928130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf6294f3f61a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('user_tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='uq_user_ticker')
    )
    op.create_index(op.f('ix_user_tickers_id'), 'user_tickers', ['id'], unique=False)
    op.add_column('backtest_results', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_backtest_results_user_id'), 'backtest_results', ['user_id'], unique=False)
    op.create_foreign_key(None, 'backtest_results', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('portfolio_results', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_portfolio_results_user_id'), 'portfolio_results', ['user_id'], unique=False)
    op.create_foreign_key(None, 'portfolio_results', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('research_results', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_research_results_user_id'), 'research_results', ['user_id'], unique=False)
    op.create_foreign_key(None, 'research_results', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('shap_results', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shap_results_user_id'), 'shap_results', ['user_id'], unique=False)
    op.create_foreign_key(None, 'shap_results', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shap_results', type_='foreignkey')
    op.drop_index(op.f('ix_shap_results_user_id'), table_name='shap_results')
    op.drop_column('shap_results', 'user_id')
    op.drop_constraint(None, 'research_results', type_='foreignkey')
    op.drop_index(op.f('ix_research_results_user_id'), table_name='research_results')
    op.drop_column('research_results', 'user_id')
    op.drop_constraint(None, 'portfolio_results', type_='foreignkey')
    op.drop_index(op.f('ix_portfolio_results_user_id'), table_name='portfolio_results')
    op.drop_column('portfolio_results', 'user_id')
    op.drop_constraint(None, 'backtest_results', type_='foreignkey')
    op.drop_index(op.f('ix_backtest_results_user_id'), table_name='backtest_results')
    op.drop_column('backtest_results', 'user_id')
    op.drop_index(op.f('ix_user_tickers_id'), table_name='user_tickers')
    op.drop_table('user_tickers')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
